log:
  level: INFO

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

tls:
  certificates:
    - certFile: /etc/traefik/tls/certs/cert.crt
      keyFile: /etc/traefik/tls/certs/cert.key

providers:
  docker:
    exposedByDefault: false
    network: example-voting-app_front-tier
    defaultRule: Host(`{{ index .Labels "com.docker.compose.service" }}.localhost`)

# metrics:
#   addInternals: true
